### ISSUE TITLE
Generate an HTML document from an issue XML document

### ISSUE THREAD

**Issue by chrismear** [chrismear/rails-lighthouse-archive#1]

**Comment by lovitt** [comment]
Hey Chris, I just left a comment on [Rails Issue 404](https://github.com/rails/rails/issues/404#issuecomment-1542268) (aptly ID'ed!) discussing the thousands-of-vanished-Rails-tickets conundrum. I'm happy to help generate a static website from the old tickets you captured if it seems like that is the best way to archive and publish this content. Perhaps we can use [GitHub Pages](http://pages.github.com/) to publish the site right in this repo.

**Comment by chrismear** [comment]
Hey, thanks for taking a look at this (I lol'd at the 404 too). Yeah, I think generating some static HTML is probably the best approach -- it's a snapshot of content that won't change, so we only ought to do the processing once. Using Github Pages is a good idea!

I'd greatly appreciate anything you can contribute to this; I grabbed the data quickly, but haven't had time since then to really dig into transforming it to HTML.
